packages:
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
packageExtensions:
  react-router-dom@*:
    peerDependencies:
      '@types/react': '*'
    peerDependenciesMeta:
      '@types/react':
        optional: true
  react-router@*:
    peerDependencies:
      '@types/react': '*'
    peerDependenciesMeta:
      '@types/react':
        optional: true
  '@tanstack/react-query@*':
    peerDependencies:
      '@types/react': '*'
    peerDependenciesMeta:
      '@types/react':
        optional: true
